### ISSUE TITLE
hi not sure how to contact you but il do it here

### ISSUE THREAD

**Issue by gulafaran** [ny4rlk0/BIOS-ACER-NITRO-5-AN515-45#1]
i have an an AN515-45 too, incase you ever get it fixed i managed to enter advanced bios settings with this https://github.com/Maxinator500/SREP-Patches and https://github.com/SmokelessCPUv2/SmokelessRuntimeEFIPatcher , but i havent dared touched any settings incase i brick it :)

**Comment by ny4rlk0** [comment]
Thanks, but i messed up soldering and ripped off the pads leading to bios. I think i did flashed new one correctly but, it lost it's meaning once board became too messy.
